improvement/5901
webduinoio/webduino-remote pull request #13
Opened 2022-11-02 15:15 UTC by chaoyen1111

處理中間圖片跟隨螢幕大小改變位置 [5901](https://redmine.kingkit.codes/issues/5901)

- 調整前：

![萬用遙控器-未處理](https://user-images.githubusercontent.com/74292736/199527528-aa9980fc-48f5-4cb8-a081-775965dbb94a.gif)

- 調整後：

![萬用遙控器](https://user-images.githubusercontent.com/74292736/199527706-29c58d18-7b2c-4a60-88c1-7464e5ef2e7b.gif)

2022-11-03 00:52 UTC, shengyuan requested changes
日期怎麼也刪除了... 🤣

2022-11-03 01:22 UTC, chaoyen1111 commented
因為我思考的是不是要合進 gh-pages 時候再給個最終日期就好...？:thinking:

2022-11-04 02:20 UTC, shengyuan commented on js/main.js
> +  screenRotate();
請問為什麼，上方 19~31 的程式還需要留著？考古嗎... 😅

2022-11-04 02:51 UTC, chaoyen1111 commented on js/main.js
> +  screenRotate();
我要當考古學家...（誤
要發問～請問聖原大大他有些變數是下面會用到的，不留嗎～？
然後他是載入畫面時候定位圖片位置（目前不留車子會歪一邊），最下方處理的是事件監聽當我改變視窗大小，這些東西的數值跟隨改變的椰？

2022-11-04 02:55 UTC, shengyuan approved these changes

2022-11-04 02:55 UTC, merged

2022-11-07 00:36 UTC, shengyuan commented
事後想想，請確認，當畫面旋轉後，拖拉是否有符合預期！