Bug/5899
webduinoio/webduino-remote pull request #14
Opened 2022-11-03 06:28 UTC by chaoyen1111

**bug [5899](https://redmine.kingkit.codes/issues/5899)**

- 平板開啟萬用遙控器時，訊息傳送輸入框消失
- 在 input 輸入文字時，網址會消失重整之後會 404

![input問題](https://user-images.githubusercontent.com/74292736/199657657-5d578cea-e56b-4777-9ec7-c045fa7a43a1.gif)

**調整後**

- 平板輸入匡

![ezgif-3-1fecff3f38](https://user-images.githubusercontent.com/74292736/199658608-d21276fd-420e-4b72-a12d-486fbfc65094.gif)

- input 輸入文字時網址維持

![input](https://user-images.githubusercontent.com/74292736/199658824-18d27421-d6e3-4323-8fc5-1dee819a6aa3.gif)

2022-11-04 02:40 UTC, shengyuan requested changes
英文的版本， 建議內容中文字盡可能替換成英文，
其中的 meta 其實都有可能在搜尋引擎中呈現。

2022-11-04 02:40 UTC, shengyuan commented on css/main.css
> +  appearance: none;
這個 log 的排板挺特別的，通常是放在後方 (如 520 行的寫法)，
或是放在目標的上方，如下方的寫法，
建議可以調整一下。

``` css

/* Safari 和 Chrome，常用於iOS下移除內建樣式 */
-webkit-appearance: none;

```

2022-11-04 02:40 UTC, shengyuan commented on index-en.html
> +    <title>Webduino 萬用遙控器</title>
這個檔案目的是呈現英文語系版本的，建議調整 title 為英文版本。

2022-11-04 03:59 UTC, chaoyen1111 commented on css/main.css
> +  appearance: none;
好喔 ～ 已調整

2022-11-04 03:59 UTC, chaoyen1111 commented on index-en.html
> +    <title>Webduino 萬用遙控器</title>
好低 ～ 已調整

2022-11-07 01:50 UTC, shengyuan approved these changes

2022-11-07 01:50 UTC, merged