feat: :art: Add hamburger button
webduinoio/webduino-remote pull request #6
Opened 2022-10-19 09:31 UTC by RaxCruz

## Description

[5933](https://redmine.kingkit.codes/issues/5933)

## Motivation and Context

切版- Hamburger Button

## How Has This Been Tested?

## Screenshots (if appropriate)

![截圖 2022-10-19 下午5 30 40](https://user-images.githubusercontent.com/39622968/196653804-133e7f77-d36c-41f0-b628-ee14449dcfaf.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-10-20 02:16 UTC, shengyuan requested changes
像是 `index.css` 這類型，目前無效果甚至是空的檔案，建議可以不用放上來。

2022-10-20 02:16 UTC, shengyuan commented on my-app/src/App.tsx
>  import { ReactComponent as Circle } from './images/circle.svg'
上次沒 review，想請問，為什麼需要 加入這個 svg ？看起來好像沒用到？

2022-10-20 02:16 UTC, shengyuan commented on my-app/src/src/Hamburger/Hamburger.tsx
> +        <ImageHamburger height={30} width={30}/>
請問這裡的寫法，為什麼需要用 `{` 包起來？

2022-10-20 03:52 UTC, RaxCruz commented on my-app/src/App.tsx
>  import { ReactComponent as Circle } from './images/circle.svg'
審查過後，是之前實作忘記刪除的部分

2022-10-25 09:45 UTC, RaxCruz commented on my-app/src/src/Hamburger/Hamburger.tsx
> +        <ImageHamburger height={30} width={30}/>
這邊是把 長寬 當作 prop 傳入 svg元件中

2022-10-26 07:29 UTC, shengyuan requested changes
建議在編輯器加上自動格式化的工具，讓程式自動編排，
在閱讀上會比較舒服。

2022-10-26 07:29 UTC, shengyuan commented on my-app/src/components/Hamburger/Hamburger.tsx
> +    <div className={"Hamburger "+(hamburgerIsShow?'':'is-active')} onClick={()=>handleHamburgerClick()}>
`is-active` 是表達什麼意思？
hamburger show 的時候，是 inactive 嗎？
hamburger hidden 時，是 active 的意思嗎？

2022-10-26 07:29 UTC, shengyuan commented on my-app/src/components/Hamburger/Hamburger.tsx
> +    <div className={"Hamburger "+(hamburgerIsShow?'':'is-active')} onClick={()=>handleHamburgerClick()}>
`onClick={handleHamburgerClick}` 可以簡潔一些。

2022-10-26 07:29 UTC, shengyuan commented on my-app/src/App.tsx
> +        <Hamburger hamburgerIsShow={hamburgerIsShow} handleHamburgerClick={handleHamburgerClick} />
建議命名調整，`hamburgerIsShow` 可以調整為 `hidden`，就像一般  html element 一樣，
當 hidden=true 時，就隱藏，反之則顯示。
使用 `hamburgerIsShow` 會比較像用在函數的命名。

2022-10-26 07:29 UTC, shengyuan commented on my-app/src/App.tsx
> +        <Hamburger hamburgerIsShow={hamburgerIsShow} handleHamburgerClick={handleHamburgerClick} />
另外，`Hamburger` 是個元件，在屬性的命名上，建議不用再加上 hamburger 的字樣，
就像 html input，事件命名會是 `onClick` 而不是 `onInputClick` 之類的。

2022-10-26 07:29 UTC, shengyuan commented on my-app/src/components/Setting/Setting.tsx
> +        popupIsShow?<SettingPopup setPopupIsShow={setPopupIsShow}/>:""
建議調整如下，適當的空格，會好讀一些。
`popupIsShow ? <SettingPopup setPopupIsShow={setPopupIsShow} /> : ""`

2022-10-26 07:29 UTC, shengyuan commented on my-app/src/components/SettingList/SettingList.tsx
> +            <SettingListItem settingInfo={settingInfo}/>
建議加上一些空格，方便閱讀

```
{settingInfos.map((settingInfo:any) => (
    <SettingListItem settingInfo={settingInfo} />
```

2022-10-26 07:31 UTC, shengyuan commented
另外，標題的內容是一顆按鈕，但改動的內容，是一個頁面，
有點不太符合，建議調整命名。

2022-10-26 08:04 UTC, RaxCruz commented on my-app/src/components/Hamburger/Hamburger.tsx
> +    <div className={"Hamburger "+(hamburgerIsShow?'':'is-active')} onClick={()=>handleHamburgerClick()}>
已調整

2022-10-26 08:04 UTC, RaxCruz commented on my-app/src/App.tsx
> +        <Hamburger hamburgerIsShow={hamburgerIsShow} handleHamburgerClick={handleHamburgerClick} />
已調整

2022-10-26 08:04 UTC, RaxCruz commented on my-app/src/components/Setting/Setting.tsx
> +        popupIsShow?<SettingPopup setPopupIsShow={setPopupIsShow}/>:""
已調整

2022-10-26 08:04 UTC, RaxCruz commented on my-app/src/components/SettingList/SettingList.tsx
> +            <SettingListItem settingInfo={settingInfo}/>
已調整

2022-10-26 09:02 UTC, shengyuan commented on my-app/src/components/SettingPopup/SettingPopup.tsx
> +      <div className="SettingPopup-copyBtn" data-clipboard-target="#saveUrl">
這個複製的 target `#saveUrl` 是怎麼處理？

2022-11-08 05:21 UTC, closed without merging